create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile text not null default 'ashay' check (profile in ('ashay', 'girlfriend')),
  session_name text not null,
  exercise text not null,
  weight_kg numeric(7,2) not null check (weight_kg >= 0),
  reps integer not null check (reps > 0),
  rir integer not null check (rir between 0 and 10),
  performed_at timestamptz not null default now()
);

create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile text not null default 'ashay' check (profile in ('ashay', 'girlfriend')),
  measured_at date not null default current_date,
  weight_kg numeric(6,2) not null check (weight_kg > 0),
  waist_cm numeric(6,2), chest_cm numeric(6,2), arm_cm numeric(6,2),
  thigh_cm numeric(6,2), hip_cm numeric(6,2), neck_cm numeric(6,2)
);

alter table public.workout_sets enable row level security;
alter table public.measurements enable row level security;

create policy "Users manage own workout sets" on public.workout_sets
  for all using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage own measurements" on public.measurements
  for all using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create index if not exists workout_sets_user_date_idx on public.workout_sets(user_id, performed_at desc);
create index if not exists measurements_user_date_idx on public.measurements(user_id, measured_at desc);
